CREATE DATABASE IF NOT EXISTS wpDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE USER IF NOT EXISTS 'berna'@'localhost' IDENTIFIED BY 'Berna123';
GRANT ALL ON wpDB.* TO 'berna'@'localhost';
FLUSH PRIVILEGES;

